version: '3.9'
services:
  principal-service:
    build:
      dockerfile: dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_USERNAME=devuser
      - DB_PASSWORD=devpassword
      - DB_URL=jdbc:postgresql://postgres:5432/devdb
      - HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - 5432:5432
volumes:
  redis_data:

